# Generated by Django 5.0.2 on 2024-03-05 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=10, unique=True)),
                ('second_id', models.IntegerField(unique=True)),
                ('movieId', models.IntegerField(unique=True)),
                ('adult', models.BooleanField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('belongs_to_collection', models.JSONField(blank=True)),
                ('budget', models.IntegerField(blank=True)),
                ('homepage', models.CharField(blank=True, max_length=200)),
                ('original_language', models.CharField(blank=True, max_length=5)),
                ('original_title', models.CharField(blank=True, max_length=50)),
                ('overview', models.CharField(blank=True, max_length=900)),
                ('popularity', models.FloatField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=100)),
                ('production_companies', models.JSONField(blank=True)),
                ('production_countries', models.JSONField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('year', models.SmallIntegerField(blank=True)),
                ('revenue', models.FloatField(blank=True)),
                ('runtime', models.FloatField(blank=True)),
                ('spoken_languages', models.JSONField(blank=True)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('tagline', models.CharField(blank=True, max_length=900)),
                ('video', models.BooleanField(blank=True)),
                ('vote_average', models.FloatField(blank=True)),
                ('vote_count', models.FloatField(blank=True)),
                ('cast', models.JSONField(blank=True)),
                ('crew', models.JSONField(blank=True)),
                ('keywords', models.JSONField(blank=True)),
                ('cast_size', models.SmallIntegerField(blank=True)),
                ('crew_size', models.SmallIntegerField(blank=True)),
                ('genres', models.JSONField(blank=True)),
                ('director', models.CharField(blank=True, max_length=50)),
                ('actors', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
